event repo & domain service
jruan1580/Rof-Scheduler pull request #202
Opened 2022-10-19 02:18 UTC by bwruan

2022-10-19 23:43 UTC, jruan1580 requested changes

2022-10-19 23:43 UTC, jruan1580 commented on Database/Table Scripts/CreateEventsTableScript.sql
> +CREATE TABLE dbo.JobEvent(
Let's add one more field:

Canceled - boolean

This will be set to true when someone cancels and it will not be displayed on the calendar

2022-10-19 23:43 UTC, jruan1580 commented on EventsManagementService/EventManagementService.Domain/Mappers/EventMapper.cs
> +            coreEvent.Employee = new Models.Employee() { Id = dbEvent.EmployeeId, FirstName = dbEvent.Employee.FirstName, LastName = dbEvent.Employee.LastName, Role = dbEvent.Employee.Role };
There's a potential for bug here and you've done this before.

What happens in dbEvent.Employee is null?

2022-10-19 23:43 UTC, jruan1580 commented on EventsManagementService/EventManagementService.Domain/Mappers/EventMapper.cs
> +            coreEvent.PetService = new Models.PetService() { Id = dbEvent.PetServiceId, ServiceName = dbEvent.PetService.ServiceName, Description = dbEvent.PetService.Description, Price = dbEvent.Pet
All these same as above comment ^^.

2022-10-20 23:26 UTC, bwruan commented
Addressed

2022-10-20 23:27 UTC, jruan1580 approved these changes

2022-10-20 23:27 UTC, merged