Unit Test: Get Employee & Employee Mapper
jruan1580/Rof-Scheduler pull request #49
Opened 2022-02-08 04:59 UTC by bwruan

2022-02-09 02:17 UTC, jruan1580 commented on EmployeeManagementService/EmployeeManagementService.Domain/Services/EmployeeService.cs
>              var employees = await _employeeRepository.GetAllEmployees(page, offset);
check if employees is null or empty, return an empty list.

2022-02-09 02:18 UTC, jruan1580 commented on EmployeeManagementService/EmployeeManagementService.Test/Mapper/EmployeeMapperTest.cs
> +            Assert.AreEqual("John Doe", entity.FullName);
check if SSN was sanitize

2022-02-09 02:20 UTC, jruan1580 requested changes
address comments

2022-02-10 01:56 UTC, bwruan commented
Done

2022-02-10 01:58 UTC, merged